/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_ATprofile = 1,
  anon_sym_ATdescription = 2,
  anon_sym_ATend = 3,
  anon_sym_ATsection = 4,
  sym_section_name = 5,
  anon_sym_COLON = 6,
  anon_sym_string = 7,
  anon_sym_number = 8,
  anon_sym_bool = 9,
  anon_sym_percentage = 10,
  anon_sym_ATif = 11,
  anon_sym_ATelse = 12,
  anon_sym_ATendif = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_LT_EQ = 17,
  anon_sym_GT = 18,
  anon_sym_LT = 19,
  anon_sym_and = 20,
  anon_sym_or = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_pct = 24,
  anon_sym_PERCENT = 25,
  sym_numbered_marker = 26,
  sym_bullet_marker = 27,
  anon_sym_LBRACE_LBRACE = 28,
  anon_sym_RBRACE_RBRACE = 29,
  sym_text_segment = 30,
  sym_identifier = 31,
  sym_number = 32,
  anon_sym_true = 33,
  anon_sym_false = 34,
  sym_line_end = 35,
  sym_source_file = 36,
  sym_profile_directive = 37,
  sym_description_directive = 38,
  sym_section = 39,
  sym_section_header = 40,
  sym_declaration_line = 41,
  sym_type_name = 42,
  sym_conditional_directive = 43,
  sym_conditional_expression = 44,
  sym_comparison_expression = 45,
  sym_logical_expression = 46,
  sym_parenthesized_expression = 47,
  sym_operand = 48,
  sym_percent_helper_expression = 49,
  sym_percentage_literal = 50,
  sym_list_item = 51,
  sym_inline_text = 52,
  sym_text_line = 53,
  sym_placeholder = 54,
  sym_empty_line = 55,
  sym_boolean = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_description_directive_repeat1 = 58,
  aux_sym_section_repeat1 = 59,
  aux_sym_inline_text_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_ATprofile] = "directive_keyword",
  [anon_sym_ATdescription] = "directive_keyword",
  [anon_sym_ATend] = "directive_keyword",
  [anon_sym_ATsection] = "directive_keyword",
  [sym_section_name] = "section_name",
  [anon_sym_COLON] = ":",
  [anon_sym_string] = "string",
  [anon_sym_number] = "number",
  [anon_sym_bool] = "bool",
  [anon_sym_percentage] = "percentage",
  [anon_sym_ATif] = "directive_keyword",
  [anon_sym_ATelse] = "directive_keyword",
  [anon_sym_ATendif] = "directive_keyword",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_pct] = "pct",
  [anon_sym_PERCENT] = "%",
  [sym_numbered_marker] = "numbered_marker",
  [sym_bullet_marker] = "bullet_marker",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_text_segment] = "text_segment",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_line_end] = "line_end",
  [sym_source_file] = "source_file",
  [sym_profile_directive] = "profile_directive",
  [sym_description_directive] = "description_directive",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym_declaration_line] = "declaration_line",
  [sym_type_name] = "type_name",
  [sym_conditional_directive] = "conditional_directive",
  [sym_conditional_expression] = "conditional_expression",
  [sym_comparison_expression] = "comparison_expression",
  [sym_logical_expression] = "logical_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_operand] = "operand",
  [sym_percent_helper_expression] = "percent_helper_expression",
  [sym_percentage_literal] = "percentage_literal",
  [sym_list_item] = "list_item",
  [sym_inline_text] = "inline_text",
  [sym_text_line] = "text_line",
  [sym_placeholder] = "placeholder",
  [sym_empty_line] = "empty_line",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_description_directive_repeat1] = "description_directive_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_inline_text_repeat1] = "inline_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_ATprofile] = anon_sym_ATprofile,
  [anon_sym_ATdescription] = anon_sym_ATprofile,
  [anon_sym_ATend] = anon_sym_ATprofile,
  [anon_sym_ATsection] = anon_sym_ATprofile,
  [sym_section_name] = sym_section_name,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_percentage] = anon_sym_percentage,
  [anon_sym_ATif] = anon_sym_ATprofile,
  [anon_sym_ATelse] = anon_sym_ATprofile,
  [anon_sym_ATendif] = anon_sym_ATprofile,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_pct] = anon_sym_pct,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_numbered_marker] = sym_numbered_marker,
  [sym_bullet_marker] = sym_bullet_marker,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_text_segment] = sym_text_segment,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_line_end] = sym_line_end,
  [sym_source_file] = sym_source_file,
  [sym_profile_directive] = sym_profile_directive,
  [sym_description_directive] = sym_description_directive,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym_declaration_line] = sym_declaration_line,
  [sym_type_name] = sym_type_name,
  [sym_conditional_directive] = sym_conditional_directive,
  [sym_conditional_expression] = sym_conditional_expression,
  [sym_comparison_expression] = sym_comparison_expression,
  [sym_logical_expression] = sym_logical_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_operand] = sym_operand,
  [sym_percent_helper_expression] = sym_percent_helper_expression,
  [sym_percentage_literal] = sym_percentage_literal,
  [sym_list_item] = sym_list_item,
  [sym_inline_text] = sym_inline_text,
  [sym_text_line] = sym_text_line,
  [sym_placeholder] = sym_placeholder,
  [sym_empty_line] = sym_empty_line,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_description_directive_repeat1] = aux_sym_description_directive_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_inline_text_repeat1] = aux_sym_inline_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_ATprofile] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATdescription] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATsection] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_percentage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATendif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_numbered_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_bullet_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_text_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_line_end] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_profile_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_description_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_line] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_percent_helper_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_percentage_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_inline_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_condition = 2,
  field_content = 3,
  field_end_keyword = 4,
  field_keyword = 5,
  field_name = 6,
  field_operator = 7,
  field_profile = 8,
  field_type = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_condition] = "condition",
  [field_content] = "content",
  [field_end_keyword] = "end_keyword",
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_profile] = "profile",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 1},
  [13] = {.index = 17, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
    {field_profile, 1},
  [2] =
    {field_content, 1},
    {field_keyword, 0},
  [4] =
    {field_keyword, 0},
    {field_name, 1},
  [6] =
    {field_condition, 1},
  [7] =
    {field_content, 1},
  [8] =
    {field_name, 1},
  [9] =
    {field_end_keyword, 1},
  [10] =
    {field_end_keyword, 2},
    {field_keyword, 0},
  [12] =
    {field_operator, 1},
  [13] =
    {field_end_keyword, 2},
  [14] =
    {field_end_keyword, 3},
    {field_keyword, 0},
  [16] =
    {field_argument, 2},
  [17] =
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static const TSCharacterRange sym_text_segment_character_set_1[] = {
  {0, '\t'}, {0x0b, '\''}, {'*', '9'}, {';', '?'}, {'A', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(74);
      ADVANCE_MAP(
        '\n', 128,
        '!', 4,
        '%', 100,
        '(', 96,
        ')', 97,
        ':', 80,
        '<', 93,
        '=', 5,
        '>', 92,
        '@', 13,
        'a', 40,
        'b', 45,
        'f', 6,
        'n', 66,
        'o', 51,
        'p', 9,
        's', 64,
        't', 54,
        '{', 68,
        '}', 69,
        '*', 103,
        '-', 103,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(128);
      if (lookahead == '{') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != '@' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(111);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(96);
      if (lookahead == 'f') ADVANCE(112);
      if (lookahead == 'p') ADVANCE(113);
      if (lookahead == 't') ADVANCE(117);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(88);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(61);
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(63);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 'p') ADVANCE(56);
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(94);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(77);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(124);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(85);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(87);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(81);
      END_STATE();
    case 29:
      if (lookahead == 'g') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(59);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 50:
      if (lookahead == 'p') ADVANCE(65);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 60:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(98);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 66:
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 67:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 68:
      if (lookahead == '{') ADVANCE(105);
      END_STATE();
    case 69:
      if (lookahead == '}') ADVANCE(106);
      END_STATE();
    case 70:
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 71:
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 73:
      if (eof) ADVANCE(74);
      ADVANCE_MAP(
        '\n', 128,
        '@', 13,
        '{', 68,
        '*', 104,
        '-', 104,
        '\t', 108,
        '\f', 108,
        '\r', 108,
        ' ', 108,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '0' || ':' < lookahead) &&
          (lookahead < '@' || '[' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(111);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_ATprofile);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_ATdescription);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_ATend);
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_ATsection);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_section_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_percentage);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_ATif);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_ATelse);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_ATendif);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(91);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_pct);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_pct);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_numbered_marker);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_numbered_marker);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_bullet_marker);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_bullet_marker);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_text_segment);
      if (lookahead == '.') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_text_segment);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_text_segment);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(109);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text_segment);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text_segment);
      if ((!eof && set_contains(sym_text_segment_character_set_1, 9, lookahead))) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(116);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(119);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(118);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(120);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(115);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(114);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_line_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 73},
  [2] = {.lex_state = 73},
  [3] = {.lex_state = 73},
  [4] = {.lex_state = 73},
  [5] = {.lex_state = 73},
  [6] = {.lex_state = 73},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 73},
  [9] = {.lex_state = 73},
  [10] = {.lex_state = 73},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 73},
  [13] = {.lex_state = 73},
  [14] = {.lex_state = 73},
  [15] = {.lex_state = 73},
  [16] = {.lex_state = 73},
  [17] = {.lex_state = 73},
  [18] = {.lex_state = 73},
  [19] = {.lex_state = 73},
  [20] = {.lex_state = 73},
  [21] = {.lex_state = 73},
  [22] = {.lex_state = 73},
  [23] = {.lex_state = 73},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 73},
  [34] = {.lex_state = 73},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 70},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 71},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 71},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 71},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_ATprofile] = ACTIONS(1),
    [anon_sym_ATdescription] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATsection] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_percentage] = ACTIONS(1),
    [anon_sym_ATif] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATendif] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_pct] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_numbered_marker] = ACTIONS(1),
    [sym_bullet_marker] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_line_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym_profile_directive] = STATE(3),
    [sym_description_directive] = STATE(3),
    [sym_section] = STATE(3),
    [sym_section_header] = STATE(4),
    [sym_conditional_directive] = STATE(3),
    [sym_list_item] = STATE(3),
    [sym_text_line] = STATE(3),
    [sym_placeholder] = STATE(41),
    [sym_empty_line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_inline_text_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_ATprofile] = ACTIONS(5),
    [anon_sym_ATdescription] = ACTIONS(7),
    [anon_sym_ATsection] = ACTIONS(9),
    [anon_sym_ATif] = ACTIONS(11),
    [anon_sym_ATelse] = ACTIONS(13),
    [anon_sym_ATendif] = ACTIONS(13),
    [sym_numbered_marker] = ACTIONS(15),
    [sym_bullet_marker] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [sym_text_segment] = ACTIONS(19),
    [sym_line_end] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_ATprofile,
    ACTIONS(28), 1,
      anon_sym_ATdescription,
    ACTIONS(31), 1,
      anon_sym_ATsection,
    ACTIONS(34), 1,
      anon_sym_ATif,
    ACTIONS(43), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(46), 1,
      sym_text_segment,
    ACTIONS(49), 1,
      sym_line_end,
    STATE(4), 1,
      sym_section_header,
    ACTIONS(37), 2,
      anon_sym_ATelse,
      anon_sym_ATendif,
    ACTIONS(40), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(2), 8,
      sym_profile_directive,
      sym_description_directive,
      sym_section,
      sym_conditional_directive,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_source_file_repeat1,
  [50] = 13,
    ACTIONS(5), 1,
      anon_sym_ATprofile,
    ACTIONS(7), 1,
      anon_sym_ATdescription,
    ACTIONS(9), 1,
      anon_sym_ATsection,
    ACTIONS(11), 1,
      anon_sym_ATif,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_text_segment,
    ACTIONS(21), 1,
      sym_line_end,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_section_header,
    ACTIONS(13), 2,
      anon_sym_ATelse,
      anon_sym_ATendif,
    ACTIONS(15), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(2), 8,
      sym_profile_directive,
      sym_description_directive,
      sym_section,
      sym_conditional_directive,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_source_file_repeat1,
  [100] = 10,
    ACTIONS(11), 1,
      anon_sym_ATif,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_text_segment,
    ACTIONS(21), 1,
      sym_line_end,
    ACTIONS(54), 1,
      anon_sym_ATend,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_ATelse,
      anon_sym_ATendif,
    ACTIONS(15), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(5), 6,
      sym_declaration_line,
      sym_conditional_directive,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_section_repeat1,
  [139] = 10,
    ACTIONS(11), 1,
      anon_sym_ATif,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_text_segment,
    ACTIONS(21), 1,
      sym_line_end,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_ATend,
    ACTIONS(13), 2,
      anon_sym_ATelse,
      anon_sym_ATendif,
    ACTIONS(15), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(6), 6,
      sym_declaration_line,
      sym_conditional_directive,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_section_repeat1,
  [178] = 10,
    ACTIONS(60), 1,
      anon_sym_ATend,
    ACTIONS(62), 1,
      anon_sym_ATif,
    ACTIONS(71), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(74), 1,
      sym_text_segment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(80), 1,
      sym_line_end,
    ACTIONS(65), 2,
      anon_sym_ATelse,
      anon_sym_ATendif,
    ACTIONS(68), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(6), 6,
      sym_declaration_line,
      sym_conditional_directive,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_section_repeat1,
  [217] = 10,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_pct,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 1,
      sym_number,
    STATE(29), 1,
      sym_percentage_literal,
    STATE(35), 1,
      sym_operand,
    STATE(63), 1,
      sym_conditional_expression,
    ACTIONS(91), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 2,
      sym_comparison_expression,
      sym_logical_expression,
    STATE(28), 3,
      sym_parenthesized_expression,
      sym_percent_helper_expression,
      sym_boolean,
  [252] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [271] = 2,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [290] = 2,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [309] = 10,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_pct,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(89), 1,
      sym_number,
    STATE(29), 1,
      sym_percentage_literal,
    STATE(35), 1,
      sym_operand,
    STATE(57), 1,
      sym_conditional_expression,
    ACTIONS(91), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 2,
      sym_comparison_expression,
      sym_logical_expression,
    STATE(28), 3,
      sym_parenthesized_expression,
      sym_percent_helper_expression,
      sym_boolean,
  [344] = 2,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [363] = 2,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [382] = 2,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 13,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATend,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [401] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_text_segment,
    ACTIONS(21), 1,
      sym_line_end,
    ACTIONS(117), 1,
      anon_sym_ATend,
    ACTIONS(15), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(18), 4,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_description_directive_repeat1,
  [428] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [445] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [462] = 7,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_text_segment,
    ACTIONS(21), 1,
      sym_line_end,
    ACTIONS(127), 1,
      anon_sym_ATend,
    ACTIONS(15), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(21), 4,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_description_directive_repeat1,
  [489] = 2,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [506] = 2,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [523] = 7,
    ACTIONS(137), 1,
      anon_sym_ATend,
    ACTIONS(142), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(145), 1,
      sym_text_segment,
    ACTIONS(148), 1,
      sym_line_end,
    ACTIONS(139), 2,
      sym_numbered_marker,
      sym_bullet_marker,
    STATE(41), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
    STATE(21), 4,
      sym_list_item,
      sym_text_line,
      sym_empty_line,
      aux_sym_description_directive_repeat1,
  [550] = 2,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [567] = 2,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 11,
      anon_sym_ATprofile,
      anon_sym_ATdescription,
      anon_sym_ATsection,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_line_end,
  [584] = 4,
    ACTIONS(165), 1,
      anon_sym_PERCENT,
    ACTIONS(161), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(163), 2,
      anon_sym_RPAREN,
      sym_line_end,
    ACTIONS(159), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
  [604] = 7,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_pct,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_number,
    STATE(45), 1,
      sym_operand,
    ACTIONS(91), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(29), 4,
      sym_parenthesized_expression,
      sym_percent_helper_expression,
      sym_percentage_literal,
      sym_boolean,
  [630] = 7,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_pct,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_number,
    STATE(46), 1,
      sym_operand,
    ACTIONS(91), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(29), 4,
      sym_parenthesized_expression,
      sym_percent_helper_expression,
      sym_percentage_literal,
      sym_boolean,
  [656] = 2,
    ACTIONS(173), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(171), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      sym_line_end,
  [671] = 3,
    ACTIONS(161), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(163), 2,
      anon_sym_RPAREN,
      sym_line_end,
    ACTIONS(159), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
  [688] = 2,
    ACTIONS(161), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(159), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      sym_line_end,
  [703] = 2,
    ACTIONS(177), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(175), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      sym_line_end,
  [718] = 2,
    ACTIONS(181), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(179), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      sym_line_end,
  [733] = 2,
    ACTIONS(185), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(183), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RPAREN,
      sym_line_end,
  [748] = 1,
    ACTIONS(187), 10,
      anon_sym_ATend,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [761] = 1,
    ACTIONS(189), 10,
      anon_sym_ATend,
      anon_sym_ATif,
      anon_sym_ATelse,
      anon_sym_ATendif,
      sym_numbered_marker,
      sym_bullet_marker,
      anon_sym_LBRACE_LBRACE,
      sym_text_segment,
      sym_identifier,
      sym_line_end,
  [774] = 3,
    ACTIONS(193), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(195), 2,
      anon_sym_and,
      anon_sym_or,
    ACTIONS(191), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [789] = 5,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(197), 1,
      sym_text_segment,
    ACTIONS(199), 1,
      sym_line_end,
    STATE(68), 1,
      sym_inline_text,
    STATE(40), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
  [806] = 5,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(197), 1,
      sym_text_segment,
    ACTIONS(201), 1,
      sym_line_end,
    STATE(61), 1,
      sym_inline_text,
    STATE(40), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
  [823] = 2,
    STATE(64), 1,
      sym_type_name,
    ACTIONS(203), 4,
      anon_sym_string,
      anon_sym_number,
      anon_sym_bool,
      anon_sym_percentage,
  [833] = 4,
    ACTIONS(205), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(208), 1,
      sym_text_segment,
    ACTIONS(211), 1,
      sym_line_end,
    STATE(39), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
  [847] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(213), 1,
      sym_text_segment,
    ACTIONS(215), 1,
      sym_line_end,
    STATE(39), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
  [861] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(213), 1,
      sym_text_segment,
    ACTIONS(217), 1,
      sym_line_end,
    STATE(39), 2,
      sym_placeholder,
      aux_sym_inline_text_repeat1,
  [875] = 2,
    ACTIONS(221), 1,
      sym_text_segment,
    ACTIONS(219), 2,
      anon_sym_LBRACE_LBRACE,
      sym_line_end,
  [883] = 2,
    ACTIONS(165), 1,
      anon_sym_PERCENT,
    ACTIONS(159), 2,
      anon_sym_RPAREN,
      sym_line_end,
  [891] = 1,
    ACTIONS(163), 2,
      anon_sym_RPAREN,
      sym_line_end,
  [896] = 1,
    ACTIONS(223), 2,
      anon_sym_RPAREN,
      sym_line_end,
  [901] = 1,
    ACTIONS(225), 2,
      anon_sym_RPAREN,
      sym_line_end,
  [906] = 1,
    ACTIONS(227), 1,
      sym_line_end,
  [910] = 1,
    ACTIONS(229), 1,
      anon_sym_RBRACE_RBRACE,
  [914] = 1,
    ACTIONS(231), 1,
      sym_line_end,
  [918] = 1,
    ACTIONS(233), 1,
      anon_sym_COLON,
  [922] = 1,
    ACTIONS(235), 1,
      anon_sym_LPAREN,
  [926] = 1,
    ACTIONS(237), 1,
      sym_section_name,
  [930] = 1,
    ACTIONS(239), 1,
      sym_line_end,
  [934] = 1,
    ACTIONS(241), 1,
      sym_identifier,
  [938] = 1,
    ACTIONS(243), 1,
      sym_line_end,
  [942] = 1,
    ACTIONS(245), 1,
      sym_line_end,
  [946] = 1,
    ACTIONS(247), 1,
      sym_line_end,
  [950] = 1,
    ACTIONS(249), 1,
      sym_line_end,
  [954] = 1,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
  [958] = 1,
    ACTIONS(253), 1,
      sym_identifier,
  [962] = 1,
    ACTIONS(255), 1,
      sym_line_end,
  [966] = 1,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
  [970] = 1,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
  [974] = 1,
    ACTIONS(261), 1,
      sym_line_end,
  [978] = 1,
    ACTIONS(263), 1,
      sym_identifier,
  [982] = 1,
    ACTIONS(265), 1,
      sym_line_end,
  [986] = 1,
    ACTIONS(267), 1,
      sym_line_end,
  [990] = 1,
    ACTIONS(269), 1,
      sym_line_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 139,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 252,
  [SMALL_STATE(9)] = 271,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 309,
  [SMALL_STATE(12)] = 344,
  [SMALL_STATE(13)] = 363,
  [SMALL_STATE(14)] = 382,
  [SMALL_STATE(15)] = 401,
  [SMALL_STATE(16)] = 428,
  [SMALL_STATE(17)] = 445,
  [SMALL_STATE(18)] = 462,
  [SMALL_STATE(19)] = 489,
  [SMALL_STATE(20)] = 506,
  [SMALL_STATE(21)] = 523,
  [SMALL_STATE(22)] = 550,
  [SMALL_STATE(23)] = 567,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 604,
  [SMALL_STATE(26)] = 630,
  [SMALL_STATE(27)] = 656,
  [SMALL_STATE(28)] = 671,
  [SMALL_STATE(29)] = 688,
  [SMALL_STATE(30)] = 703,
  [SMALL_STATE(31)] = 718,
  [SMALL_STATE(32)] = 733,
  [SMALL_STATE(33)] = 748,
  [SMALL_STATE(34)] = 761,
  [SMALL_STATE(35)] = 774,
  [SMALL_STATE(36)] = 789,
  [SMALL_STATE(37)] = 806,
  [SMALL_STATE(38)] = 823,
  [SMALL_STATE(39)] = 833,
  [SMALL_STATE(40)] = 847,
  [SMALL_STATE(41)] = 861,
  [SMALL_STATE(42)] = 875,
  [SMALL_STATE(43)] = 883,
  [SMALL_STATE(44)] = 891,
  [SMALL_STATE(45)] = 896,
  [SMALL_STATE(46)] = 901,
  [SMALL_STATE(47)] = 906,
  [SMALL_STATE(48)] = 910,
  [SMALL_STATE(49)] = 914,
  [SMALL_STATE(50)] = 918,
  [SMALL_STATE(51)] = 922,
  [SMALL_STATE(52)] = 926,
  [SMALL_STATE(53)] = 930,
  [SMALL_STATE(54)] = 934,
  [SMALL_STATE(55)] = 938,
  [SMALL_STATE(56)] = 942,
  [SMALL_STATE(57)] = 946,
  [SMALL_STATE(58)] = 950,
  [SMALL_STATE(59)] = 954,
  [SMALL_STATE(60)] = 958,
  [SMALL_STATE(61)] = 962,
  [SMALL_STATE(62)] = 966,
  [SMALL_STATE(63)] = 970,
  [SMALL_STATE(64)] = 974,
  [SMALL_STATE(65)] = 978,
  [SMALL_STATE(66)] = 982,
  [SMALL_STATE(67)] = 986,
  [SMALL_STATE(68)] = 990,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_line, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_line, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_directive, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_directive, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_directive, 3, 0, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_directive, 3, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3, 0, 5),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_item, 3, 0, 5),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_profile_directive, 3, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_profile_directive, 3, 0, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 7),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 7),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_directive, 4, 0, 8),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description_directive, 4, 0, 8),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_directive, 3, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description_directive, 3, 0, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_directive_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 10),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, 0, 10),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_directive, 5, 0, 11),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description_directive, 5, 0, 11),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operand, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percent_helper_expression, 4, 0, 12),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_percent_helper_expression, 4, 0, 12),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_percentage_literal, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_percentage_literal, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 3, 0, 3),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_line, 4, 0, 13),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_text_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inline_text_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_inline_text_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_text, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_placeholder, 3, 0, 6),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_placeholder, 3, 0, 6),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_expression, 3, 0, 9),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_expression, 3, 0, 9),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [257] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_prmpt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
